version: "3.8"

services:
  keycloak:
    extends:
      file: auth/docker-compose.keycloak.yaml
      service: keycloak

  redis:
    extends:
      file: cache/docker-compose.redis.yaml
      service: redis

  mongodb:
    extends:
      file: db/docker-compose.mongodb.yaml
      service: mongodb

  oracle-db:
    extends:
      file: db/docker-compose.oracle.yaml
      service: oracle-db

  loki:
    extends:
      file: logs/docker-compose.grafana.yaml
      service: loki

  grafana:
    extends:
      file: logs/docker-compose.grafana.yaml
      service: grafana

  wiremock:
    extends:
      file: wiremock/docker-compose.wiremock.yaml
      service: wiremock

volumes:
  keycloak-data:
  redis-data:
  mongo-data:
  oracle-data:
  grafana-data:
  loki-data:
  wiremock-data: