version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe

    # Porta padrão do Oracle
    ports:
      - "1521:1521"   # conexão com o banco
      - "5500:5500"   # interface web (opcional)

    environment:
      # Senha do usuário SYSTEM (admin do Oracle)
      ORACLE_PASSWORD: oracle

      # Cria um usuário adicional ao subir o container
      APP_USER: app
      APP_USER_PASSWORD: 123456789

    volumes:
      # Mantém os dados mesmo após parar o container
      - oracle-data:/opt/oracle/oradata

    restart: unless-stopped

    # Define limite mínimo recomendado (opcional, mas ajuda)
    deploy:
      resources:
        limits:
          memory: 2g